# Generated by Django 2.2.6 on 2019-11-07 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('nameOfInstitution', models.CharField(max_length=200)),
                ('dateOfIssue', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dateOfExpiry', models.DateTimeField()),
                ('courseOfStudy', models.CharField(max_length=200)),
                ('isValid', models.BooleanField()),
                ('isApproved', models.BooleanField()),
                ('startingpoint1', models.CharField(max_length=250)),
                ('endingpoint1', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('durationOfCourse', models.CharField(max_length=200)),
                ('startingpoint2', models.CharField(max_length=250)),
                ('endingpoint2', models.CharField(max_length=250)),
                ('startingpoint3', models.CharField(max_length=250)),
                ('endingpoint3', models.CharField(max_length=250)),
                ('startingpoint4', models.CharField(max_length=250)),
                ('endingpoint4', models.CharField(max_length=250)),
            ],
        ),
    ]
