# Generated by Django 2.2.6 on 2019-11-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191107_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='isValid',
            new_name='isCardValid',
        ),
    ]
