# Generated by Django 2.2.6 on 2019-11-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191107_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfExpiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateOfIssue',
            field=models.DateField(),
        ),
    ]
