# Generated by Django 2.2.6 on 2019-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191107_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='endingpoint1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='endingpoint2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='endingpoint3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='endingpoint4',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='startingpoint1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='startingpoint2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='startingpoint3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='startingpoint4',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
