# Generated by Django 2.2.6 on 2019-11-09 17:33

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20191107_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_id',
            new_name='sid',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.uploadImage),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
